package models.enums;


public enum Emoji {

    GRINNING_FACE("😀", false),
    GRINNING_FACE_BIG_EYES("😃", false),
    SMILING_FACE_SMILING_EYES("😄", false),
    BEAMING_FACE_SMILING_EYES("😁", false),
    GRINNING_SQUINTING_FACE("😆", false),
    GRINNING_FACE_SWEAT("😅", false),
    FACE_TEARS_JOY("😂", false),
    ROLLING_LAUGHING("🤣", false),
    SMILING_FACE_HALO("😇", false),
    SMILING_FACE("🙂", false),
    UPSIDE_DOWN_FACE("🙃", false),
    WINKING_FACE("😉", false),
    RELIEVED_FACE("😌", false),
    SMILING_HEART_EYES("😍", false),
    SMILING_FACE_HEARTS("🥰", false),
    FACE_BLOWING_KISS("😘", false),
    KISSING_FACE("😗", false),
    KISSING_FACE_SMILING_EYES("😙", false),
    KISSING_FACE_CLOSED_EYES("😚", false),
    FACE_SAVORING_FOOD("😋", false),
    FACE_TONGUE("😛", false),
    SQUINTING_FACE_TONGUE("😝", false),
    WINKING_FACE_TONGUE("😜", false),
    ZANY_FACE("🤪", false),
    RAISED_EYEBROW("🤨", false),
    MONOCLE_FACE("🧐", true),
    NERD_FACE("🤓", false),
    SMILING_SUNGLASSES("😎", true),
    DISGUISED_FACE("🥸", true),
    STAR_STRUCK("🤩", false),
    PARTYING_FACE("🥳", false),
    SMIRKING_FACE("😏", false),
    UNAMUSED_FACE("😒", false),
    DISAPPOINTED_FACE("😞", false),
    DOWNCAST_FACE("😔", false),
    WORRIED_FACE("😟", false),
    CONFUSED_FACE("😕", false),
    SLIGHTLY_FROWNING("🙁", false),
    FROWNING_FACE("☹️", false),
    PERSEVERING_FACE("😣", false),
    CONFOUNDED_FACE("😖", false),
    TIRED_FACE("😫", false),
    WEARY_FACE("😩", false),
    PLEADING_FACE("🥺", false),
    CRYING_FACE("😢", false),
    LOUDLY_CRYING("😭", false),
    FACE_STEAM_NOSE("😤", false),
    ANGRY_FACE("😠", true),
    POUTING_FACE("😡", false),

    DOG_FACE("🐶", false),
    CAT_FACE("🐱", false),
    MOUSE_FACE("🐭", false),
    HAMSTER_FACE("🐹", false),
    RABBIT_FACE("🐰", true),
    FOX_FACE("🦊", false),
    BEAR_FACE("🐻", false),
    PANDA_FACE("🐼", false),
    KOALA_FACE("🐨", false),
    TIGER_FACE("🐯", false),
    LION_FACE("🦁", false),
    COW_FACE("🐮", true),
    PIG_FACE("🐷", true),
    FROG_FACE("🐸", false),
    MONKEY_FACE("🐵", false),
    CHICKEN("🐔", true),
    PENGUIN("🐧", false),
    BIRD("🐦", false),
    BABY_CHICK("🐤", false),
    HATCHING_CHICK("🐣", false),
    DUCK("🦆", true),
    EAGLE("🦅", false),
    OWL("🦉", false),
    BAT("🦇", false),
    WOLF_FACE("🐺", false),
    BOAR("🐗", false),
    HORSE_FACE("🐴", true),
    UNICORN("🦄", false),
    BEE_HOUSE("🐝", true),
    BUG("🐛", false),
    BUTTERFLY("🦋", false),
    SNAIL("🐌", false),
    LADY_BEETLE("🐞", false),
    ANT("🐜", false),
    MOSQUITO("🦟", false),
    CRICKET("🦗", false),
    SPIDER("🕷️", false),
    SCORPION("🦂", false),
    TURTLE("🐢", false),
    SNAKE("🐍", false),
    LIZARD("🦎", false),
    T_REX("🦖", true),
    SAUROPOD("🦕", false),
    OCTOPUS("🐙", false),
    SQUID("🦑", false),
    SHRIMP("🦐", false),
    LOBSTER("🦞", false),
    CRAB("🦀", false),
    BLOWFISH("🐡", false),
    TROPICAL_FISH("🐠", false),
    FISH("🐟", false),
    DOLPHIN("🐬", false),
    SPOUTING_WHALE("🐳", false),
    WHALE("🐋", false),
    SHARK("🦈", false),
    CROCODILE("🐊", false),
    TIGER("🐅", false),
    LEOPARD("🐆", false),
    ZEBRA("🦓", false),
    GORILLA("🦍", false),
    CACTUS("🌵", false),
    CHRISTMAS_TREE("🎄", true),
    EVERGREEN_TREE("🌲", true),
    DECIDUOUS_TREE("🌳", true),
    PALM_TREE("🌴", true),
    SEEDLING("🌱", true),
    HERB("🌿", true),
    SHAMROCK("☘️", false),
    FOUR_LEAF_CLOVER("🍀", false),
    FURNACE("🎍", true),
    PINE_DECORATION("🎍", false),
    MAPLE_LEAF("🍁", true),

    MUSHROOM("🍄", true),
    GREEN_APPLE("🍏", true),
    RED_APPLE("🍎", true),
    PEAR("🍐", false),
    ORANGE("🍊", true),
    LEMON("🍋", false),
    BANANA("🍌", true),
    WATERMELON("🍉", false),
    GRAPES("🍇", true),
    STRAWBERRY("🍓", true),
    BLUEBERRIES("🫐", false),
    MELON("🍈", true),
    CHERRIES("🍒", false),
    PEACH("🍑", true),
    MANGO("🥭", true),
    PINEAPPLE("🍍", false),
    COCONUT("🥥", false),
    KIWI("🥝", false),
    TOMATO("🍅", true),
    EGGPLANT("🍆", true),
    AVOCADO("🥑", false),
    BROCCOLI("🥦", true),
    LEAFY_GREEN("🥬", false),
    CUCUMBER("🥒", false),
    HOT_PEPPER("🌶️", true),
    BELL_PEPPER("🫑", false),
    CORN("🌽", true),
    CARROT("🥕", false),
    OLIVE("🫒", false),
    GARLIC("🧄", true),
    ONION("🧅", true),
    POTATO("🥔", true),
    SWEET_POTATO("🍠", false),
    CROISSANT("🥐", false),
    BAGUETTE("🥖", false),
    FLATBREAD("🫓", false),
    PRETZEL("🥨", false),
    BAGEL("🥯", false),
    PANCAKES("🥞", false),
    WAFFLE("🧇", false),
    CHEESE_WEDGE("🧀", false),
    MEAT_ON_BONE("🍖", false),
    POULTRY_LEG("🍗", false),
    CUT_OF_MEAT("🥩", false),
    BACON("🥓", false),
    HAMBURGER("🍔", false),
    FRENCH_FRIES("🍟", false),
    PIZZA("🍕", false),
    HOT_DOG("🌭", false),
    SANDWICH("🥪", false),
    TACO("🌮", false),

    SOCCER_BALL("⚽", false),
    BASKETBALL("🏀", false),
    AMERICAN_FOOTBALL("🏈", false),
    BASEBALL("⚾", false),
    SOFTBALL("🥎", false),
    TENNIS("🎾", false),
    VOLLEYBALL("🏐", false),
    RUGBY_FOOTBALL("🏉", false),
    FLYING_DISC("🥏", false),
    BILLIARDS("🎱", false),
    YO_YO("🪀", false),
    PING_PONG("🏓", false),
    BADMINTON("🏸", false),
    ICE_HOCKEY("🏒", false),
    FIELD_HOCKEY("🏑", false),
    LACROSSE("🥍", false),
    CRICKET_GAME("🏏", false),
    BOOMERANG("🪃", false),
    GOAL_NET("🥅", false),
    FLAG_IN_HOLE("⛳", false),
    KITE("🪁", false),
    BOW_AND_ARROW("🏹", false),
    FISHING_POLE("🎣", false),
    DIVING_MASK("🤿", false),
    BOXING_GLOVE("🥊", false),
    LOOM("🥋", true),
    RUNNING_SHIRT("🎽", false),
    SKATEBOARD("🛹", false),
    MAYONNAISE_MACHINE("🛼", true),
    SLED("🛷", false),
    ICE_SKATE("⛸️", false),
    CURLING_STONE("🥌", false),
    DIRECT_HIT("🎯", false),
    YO_YO_ALT("🪀", false),
    VIDEO_GAME("🎮", false),
    GAME_DIE("🎲", false),
    PUZZLE("🧩", false),
    CHESS_PAWN("♟️", false),
    PERFORMING_ARTS("🎭", false),
    ARTIST_PALETTE("🎨", false),

    CAR("🚗", false),
    TAXI("🚕", false),
    SUV("🚙", false),
    BUS("🚌", false),
    TROLLEYBUS("🚎", false),
    RACING_CAR("🏎️", false),
    POLICE_CAR("🚓", false),
    AMBULANCE("🚑", false),
    FIRE_ENGINE("🚒", false),
    MINIVAN("🚐", false),
    DELIVERY_TRUCK("🚚", false),
    ARTICULATED_LORRY("🚛", false),
    TRACTOR("🚜", false),
    MOTOR_SCOOTER("🛵", false),
    MOTORCYCLE("🏍️", false),
    AUTO_RICKSHAW("🛺", false),
    BICYCLE("🚲", false),
    SCOOTER("🛴", false),
    ONCOMING_POLICE_CAR("🚔", false),
    CHARCOAL_kLIN("🚍", true),
    AIRPLANE("✈️", false),
    SMALL_AIRPLANE("🛩️", false),
    ROCKET("🚀", false),
    UFO("🛸", false),
    HELICOPTER("🚁", false),
    CANOE("🛶", false),
    SAILBOAT("⛵", false),
    SPEEDBOAT("🚤", false),
    MOTOR_BOAT("🛥️", false),
    PASSENGER_SHIP("🛳️", false),
    HOUSE("🏠", false),
    HOUSE_WITH_GARDEN("🏡", false),
    OFFICE_BUILDING("🏢", false),
    JAPANESE_POST_OFFICE("🏣", false),
    HOSPITAL("🏥", false),
    BANK("🏦", false),
    HOTEL("🏨", false),
    LOVE_HOTEL("🏩", false),
    CONVENIENCE_STORE("🏪", false),

    WATCH("⌚", false),
    MOBILE_PHONE("📱", false),
    LAPTOP("💻", false),
    KEYBOARD("⌨️", false),
    DESKTOP("🖥️", false),
    PRINTER("🖨️", false),
    MOUSE("🖱️", false),
    FLOPPY_DISK("💾", false),
    CD("💿", false),
    DVD("📀", false),
    CAMERA("📷", false),
    VIDEO_CAMERA("🎥", false),
    MAGNIFYING_GLASS_LEFT("🔍", false),
    LIGHT_BULB("💡", false),
    FLASHLIGHT("🔦", false),
    BLUE_BOOK("📘", false),
    BOOKS("📚", false),
    MEMO("📝", false),
    PENCIL("✏️", false),
    FOUNTAIN_PEN("✒️", false),
    PEN("🖊️", false),
    PAINTBRUSH("🖌️", false),
    CRAYON("🖍️", false),
    PAPERCLIP("📎", false),
    SCISSORS("✂️", false),
    LOCK("🔒", false),
    KEY("🔑", false),
    HAMMER("🔨", false),
    PICK("⛏️", false),
    HAMMER_AND_PICK("⚒️", false),
    TOOLS("🛠️", false),
    WRENCH("🔧", false),
    NUT_AND_BOLT("🔩", false),
    GEAR("⚙️", false),
    CLAMP("🗜️", false),
    SATELLITE_ANTENNA("📡", false),
    SYRINGE("💉", false),
    PILL("💊", false),
    DOOR("🚪", false),
    BED("🛏️", false),
    TOILET("🚽", false),

    RED_HEART("❤️", false),
    ORANGE_HEART("🧡", false),
    YELLOW_HEART("💛", false),
    GREEN_HEART("💚", false),
    BLUE_HEART("💙", false),
    PURPLE_HEART("💜", false),
    BROWN_HEART("🤎", false),
    BLACK_HEART("🖤", false),
    WHITE_HEART("🤍", false),
    BROKEN_HEART("💔", false),
    HEART_EXCLAMATION("❣️", false),
    TWO_HEARTS("💕", false),
    REVOLVING_HEARTS("💞", false),
    BEATING_HEART("💓", false),
    GROWING_HEART("💗", false),
    SPARKLING_HEART("💖", false),
    HEART_WITH_ARROW("💘", false),
    HEART_WITH_RIBBON("💝", false),
    HEART_DECORATION("💟", false),
    PEACE_SYMBOL("☮️", false),
    LATIN_CROSS("✝️", false),
    STAR_AND_CRESCENT("☪️", false),
    OM_SYMBOL("🕉️", false),
    WHEEL_OF_DHARMA("☸️", false),
    STAR_OF_DAVID("✡️", false),
    SIX_POINTED_STAR("🔯", false),
    PLACE_OF_WORSHIP("🛐", false),
    ATOM_SYMBOL("⚛️", false),
    ARIES("♈", false),
    TAURUS("♉", false),
    GEMINI("♊", false),
    CANCER("♋", false),
    LEO("♌", false),
    VIRGO("♍", false),
    LIBRA("♎", false),
    SCORPIO("♏", false),
    SAGITTARIUS("♐", false),
    CAPRICORN("♑", false),
    AQUARIUS("♒", false),
    PISCES("♓", false),
    OPHIUCHUS("⛎", false),

    RED_SQUARE("🟥", false),
    BLUE_SQUARE("🟦", false),
    GREEN_SQUARE("🟩", false),
    ORANGE_SQUARE("🟧", false),
    YELLOW_SQUARE("🟨", false),
    PURPLE_SQUARE("🟪", false),
    BROWN_SQUARE("🟫", false),
    BLACK_SQUARE("⬛", false),
    WHITE_SQUARE("⬜", false),

    // دایره‌ها
    RED_CIRCLE("🔴", false),
    BLUE_CIRCLE("🔵", false),
    GREEN_CIRCLE("🟢", false),
    ORANGE_CIRCLE("🟠", false),
    YELLOW_CIRCLE("🟡", true),
    PURPLE_CIRCLE("🟣", false),
    BROWN_CIRCLE("🟤", false),

    // دسته‌بندی جدید: نمادهای بازی (Game Symbols)
    BRICK("🧱", false),
    GEM("💎", false),
    CHEST("🎁", false),
    ROCK("🪨", false),
    LOCKED("🔒", false),
    TREE("🌲", true),
    WATER("🌊", false),
    MOUNTAIN("⛰️", false),
    GRASS("🌿", false),

    WAVE("🌊", false),
    DROPLET("💧", false),
    WATER_WAVE("〰️", false),
    WATERFALL("🌊", false), // (جایگزین: برخی فونت‌ها از 🌊 برای آبشار استفاده می‌کنند)
    ICE("🧊", false),
    SNOWFLAKE("❄️", false),
    CLOUD_WITH_RAIN("🌧️", false),
    HIGH_VOLTAGE("⚡", false), // (برای رعد و برق روی آب)

    BEACH("🏖️", false),
    ISLAND("🏝️", false),
    DESERT_ISLAND("🏜️", false),
    FISH_SMOKER("🌫️", true),


    //FISH("🐟"),
    //TROPICAL_FISH("🐠"),
//    BLOWFISH("🐡"),
//    SHARK("🦈"),
//    OCTOPUS("🐙"),
//    SQUID("🦑"),
//    SHRIMP("🦐"),
//    CRAB("🦀"),
//    LOBSTER("🦞"),
//    DOLPHIN("🐬"),
//    WHALE("🐋"),
    //SPOUTING_WHALE("🐳"),
    SEAL("🦭", false),
    //TURTLE("🐢"),
    SEAHORSE("🪼", false),
    STARFISH("🌟", false),
    CORAL("🪸", false),
    SHELL("🐚", false),

    // فعالیت‌های آبی
//    SAILBOAT("⛵"),
//    SPEEDBOAT("🚤"),
    FERRY("⛴️", false),
    SHIP("🚢", false),
    ANCHOR("⚓", false),
    SCUBA_MASK("🤿", false),
    LIFE_JACKET("🦺", false),
    //FISHING_POLE("🎣"),

    //    GRAPES("🍇"),
//    MELON("🍈"),
//    WATERMELON("🍉"),
    TANGERINE("🍊", false),
//    LEMON("🍋"),
//    BANANA("🍌"),
//    PINEAPPLE("🍍"),
//    MANGO("🥭"),
//    RED_APPLE("🍎"),
//    GREEN_APPLE("🍏"),
//    PEAR("🍐"),
//    PEACH("🍑"),
//    CHERRIES("🍒", true),
//    STRAWBERRY("🍓"),
//    BLUEBERRIES("🫐"),
//    KIWI("🥝"),
//    TOMATO("🍅"),

//    // سبزیجات
//    EGGPLANT("🍆"),
//    AVOCADO("🥑"),
//    BROCCOLI("🥦"),
//    LEAFY_GREEN("🥬"),
//    CUCUMBER("🥒"),
//    HOT_PEPPER("🌶️"),
//    BELL_PEPPER("🫑"),
//    CORN("🌽"),
//    CARROT("🥕"),
//    OLIVE("🫒"),
//    GARLIC("🧄"),
//    ONION("🧅"),
//    POTATO("🥔"),
//    SWEET_POTATO("🍠"),

//    CROISSANT("🥐"),
//    BAGUETTE("🥖"),
//    FLATBREAD("🫓"),
//    PRETZEL("🥨"),
//    BAGEL("🥯"),
//    PANCAKES("🥞"),
//    WAFFLE("🧇"),
    CHEESE_PRESS("🧀", true),
//    MEAT_ON_BONE("🍖"),
//    POULTRY_LEG("🍗"),
//    CUT_OF_MEAT("🥩"),
//    BACON("🥓"),
//    HAMBURGER("🍔"),
//    FRENCH_FRIES("🍟"),
//    PIZZA("🍕"),
//    HOT_DOG("🌭"),
//    SANDWICH("🥪"),
//    TACO("🌮"),
    DEHYDRATOR("🌯", true),
    TAMALE("🫔", false),
    //FALAFEL("🧆"),
    EGG("🥚", false),
    COOKING("🍳", false),
    SHALLOW_PAN("🥘", false),
    POT_OF_FOOD("🍲", false),
    FONDUE("🫕", false),
    BOWL_WITH_SPOON("🥣", false),
    GREEN_SALAD("🥗", false),
    OIL_MAKER("🍿", true),
    BUTTER("🧈", false),
    SALT("🧂", false),
    CANNED_FOOD("🥫", true),

    BABY_BOTTLE("🍼", false),
    GLASS_OF_MILK("🥛", false),
    HOT_BEVERAGE("☕", false),
    TEAPOT("🫖", false),
    TEACUP("🍵", false),
    SAKE("🍶", false),
    BOTTLE_POPPING("🍾", false),
    WINE_GLASS("🍷", false),
    COCKTAIL("🍸", false),
    TROPICAL_DRINK("🍹", false),
    BEER_MUG("🍺", false),
    CLINKING_BEERS("🍻", false),
    CLINKING_GLASSES("🥂", false),
    TUMBLER_GLASS("🥃", false),
    POURING_LIQUID("🫗", false),
    CUP_WITH_STRAW("🥤", false),
    KEG("🧋", true),
    BEVERAGE_BOX("🧃", false),
    MATE("🧉", false),

    SOFT_ICE_CREAM("🍦", false),
    SHAVED_ICE("🍧", false),
    ICE_CREAM("🍨", false),
    DOUGHNUT("🍩", false),
    COOKIE("🍪", false),
    BIRTHDAY_CAKE("🎂", false),
    SHORTCAKE("🍰", false),
    CUPCAKE("🧁", false),
    PIE("🥧", false),
    CHOCOLATE("🍫", false),
    CANDY("🍬", false),
    LOLLIPOP("🍭", false),
    CUSTARD("🍮", false),
    HONEY_POT("🍯", false),

    // ظروف و ابزار
    FORK_KNIFE("🍴", false),
    FORK_KNIFE_PLATE("🍽️", false),
    SPOON("🥄", false),
    KITCHEN_KNIFE("🔪", false),
    PRESERVE_JAR("🫙", false),
    TRUE("✅", true),
    FALSE("❌", true),

    //    ROCK("🪨"),
//    BRICK("🧱"),
    GEM_STONE("💎", false),
    //    PICK("⛏️"),
//    MOUNTAIN("⛰️"),
    VOLCANO("🌋", false),
    MOAI("🗿", false),
    SHEEP("🐑", true),

    ANCIENT_FRUIT("\uD83E\uDEBB", true),
    POWDERMELON("\uD83C\uDF48", true),
    SWEET_GEM_BERRY("\uD83D\uDC8E", true),
    YAM("\uD83C\uDF60", true),
    PUMPKIN("\uD83C\uDF83", true),
    GRAPE("\uD83C\uDF47", true),
    FAIRY_ROSE("\uD83C\uDF39", true),
    CRANBERRIES("\uD83C\uDF52", true),
    BOK_CHO("\uD83E\uDD6C", true),
    BEET("\uD83E\uDD55", true),
    ARTICHOKE("\uD83E\uDD55", true),
    AMARANTH("\uD83C\uDF3F", true),
    WHEAT("\uD83C\uDF3E", true),
    SUNFLOWER("\uD83C\uDF3B", true),
    SUMMER_SQUASH("\uD83C\uDF83", true),
    SUMMER_SPANGLE("\uD83C\uDF38", true),
    STARFRUIT("⭐", true),
    RED_CABBAGE("\uD83E\uDD6C", true),
    RADISH("\uD83C\uDF31", true),
    POPPY("\uD83C\uDF3A", true),
    HOPS("\uD83C\uDF7A", true),
    BLUEBERRY("\uD83C\uDF3D", true),
    UNMILLED_RICE("\uD83C\uDF3E", true),
    TULIP("\uD83C\uDF37", true),
    RHUBARB("\uD83C\uDF43", true),
    PARSNIP("\uD83E\uDD55", true),
    KALE("\uD83E\uDD6C", true),
    GREEN_BEAN("\uD83E\uDED8", true),
    COFFEE_BEAN("☕", true),
    CAULIFLOWER("\uD83E\uDD66", true),
    BLUE_JAZZ("\uD83C\uDFB7", true),

    BLOSSOM("\uD83C\uDF3C", true),
    CHERRY_BLOSSOM("🌸", true),
    CHESTNUT("🌰", true),

    JAZZ_SEEDS("🎷", true),
    CARROT_SEEDS("🥕", true),
    CAULIFLOWER_SEEDS("🥦", true),
//    COFFEE_BEAN("☕", true),
    GARLIC_SEEDS("🧄", true),
    BEAN_STARTER("🌱", true),
    KALE_SEEDS("🥬", true),
    PARSNIP_SEEDS("🫒", true),
    POTATO_SEEDS("🥔", true),
    RHUBARB_SEEDS("🍃", true),
    STRAWBERRY_SEEDS("🍓", true),
    TULIP_BULB("🌷", true),
    RICE_SHOOT("🌾", true),
    BLUEBERRY_SEEDS("🫐", true),
    CORN_SEEDS("🌽", true),
    HOPS_STARTER("🍺", true),
    PEPPER_SEEDS("🌶️", true),
    MELON_SEEDS("🍈", true),
    POPPY_SEEDS("🌸", true),
    RADISH_SEEDS("🌰", true),
    RED_CABBAGE_SEEDS("🥬", true),
    STARFRUIT_SEEDS("⭐", true),
    SPANGLE_SEEDS("🌼", true),
    SUMMER_SQUASH_SEEDS("🎃", true),
    SUNFLOWER_SEEDS("🌻", true),
    TOMATO_SEEDS("🍅", true),
    WHEAT_SEEDS("🌾", true),
    AMARANTH_SEEDS("🌺", true),
    ARTICHOKE_SEEDS("🌿", true),
    BEET_SEEDS("🧃", true),
    BOKCHOY_SEEDS("🥬", true),
    BROCCOLI_SEEDS("🥦", true),
    CRANBERRY_SEEDS("🫐", true),
    EGGPLANT_SEEDS("🍆", true),
    FAIRY_SEEDS("🧚", true),
    GRAPE_STARTER("🍇", true),
    PUMPKIN_SEEDS("🎃", true),
    YAM_SEEDS("🍠", true),
    RARE_SEEDS("🌟", true),
    POWDERMELON_SEEDS("🍉", true),
    ANCIENT_SEEDS("🗿", true),
    MIXED_SEEDS("🎲", true),
    ;

    private final String symbol;
    private boolean isUsed;

    Emoji(String symbol, boolean isUsed) {
        this.symbol = symbol;
        this.isUsed = isUsed;
    }

    public String getSymbol() {
        return symbol;
    }

    public static String getFormattedGuidance() {
        Emoji[] values = Emoji.values();
        StringBuilder output = new StringBuilder();
        for (Emoji value : values) {
            if (value.isUsed) {
                String formattedLine = String.format("%-" + 15 + "s", value.name());
                output.append(formattedLine).append(" : ").append(value.getSymbol()).append("\n");
            }
        }
        return output.toString();
    }

    public void use() {
        isUsed = true;
    }

    public boolean isUsed() {
        return isUsed;
    }
}