package models.enums;


import models.building.TileType;

public enum Emoji {

    GRINNING_FACE("😀"),
    GRINNING_FACE_BIG_EYES("😃"),
    SMILING_FACE_SMILING_EYES("😄"),
    BEAMING_FACE_SMILING_EYES("😁"),
    GRINNING_SQUINTING_FACE("😆"),
    GRINNING_FACE_SWEAT("😅"),
    FACE_TEARS_JOY("😂"),
    ROLLING_LAUGHING("🤣"),
    SMILING_FACE_HALO("😇"),
    SMILING_FACE("🙂"),
    UPSIDE_DOWN_FACE("🙃"),
    WINKING_FACE("😉"),
    RELIEVED_FACE("😌"),
    SMILING_HEART_EYES("😍"),
    SMILING_FACE_HEARTS("🥰"),
    FACE_BLOWING_KISS("😘"),
    KISSING_FACE("😗"),
    KISSING_FACE_SMILING_EYES("😙"),
    KISSING_FACE_CLOSED_EYES("😚"),
    FACE_SAVORING_FOOD("😋"),
    FACE_TONGUE("😛"),
    SQUINTING_FACE_TONGUE("😝"),
    WINKING_FACE_TONGUE("😜"),
    ZANY_FACE("🤪"),
    RAISED_EYEBROW("🤨"),
    MONOCLE_FACE("🧐"),
    NERD_FACE("🤓"),
    SMILING_SUNGLASSES("😎"),
    DISGUISED_FACE("🥸"),
    STAR_STRUCK("🤩"),
    PARTYING_FACE("🥳"),
    SMIRKING_FACE("😏"),
    UNAMUSED_FACE("😒"),
    DISAPPOINTED_FACE("😞"),
    DOWNCAST_FACE("😔"),
    WORRIED_FACE("😟"),
    CONFUSED_FACE("😕"),
    SLIGHTLY_FROWNING("🙁"),
    FROWNING_FACE("☹️"),
    PERSEVERING_FACE("😣"),
    CONFOUNDED_FACE("😖"),
    TIRED_FACE("😫"),
    WEARY_FACE("😩"),
    PLEADING_FACE("🥺"),
    CRYING_FACE("😢"),
    LOUDLY_CRYING("😭"),
    FACE_STEAM_NOSE("😤"),
    ANGRY_FACE("😠"),
    POUTING_FACE("😡"),

    DOG_FACE("🐶"),
    CAT_FACE("🐱"),
    MOUSE_FACE("🐭"),
    HAMSTER_FACE("🐹"),
    RABBIT_FACE("🐰"),
    FOX_FACE("🦊"),
    BEAR_FACE("🐻"),
    PANDA_FACE("🐼"),
    KOALA_FACE("🐨"),
    TIGER_FACE("🐯"),
    LION_FACE("🦁"),
    COW_FACE("🐮"),
    PIG_FACE("🐷"),
    FROG_FACE("🐸"),
    MONKEY_FACE("🐵"),
    CHICKEN("🐔"),
    PENGUIN("🐧"),
    BIRD("🐦"),
    BABY_CHICK("🐤"),
    HATCHING_CHICK("🐣"),
    DUCK("🦆"),
    EAGLE("🦅"),
    OWL("🦉"),
    BAT("🦇"),
    WOLF_FACE("🐺"),
    BOAR("🐗"),
    HORSE_FACE("🐴"),
    UNICORN("🦄"),
    HONEYBEE("🐝"),
    BUG("🐛"),
    BUTTERFLY("🦋"),
    SNAIL("🐌"),
    LADY_BEETLE("🐞"),
    ANT("🐜"),
    MOSQUITO("🦟"),
    CRICKET("🦗"),
    SPIDER("🕷️"),
    SCORPION("🦂"),
    TURTLE("🐢"),
    SNAKE("🐍"),
    LIZARD("🦎"),
    T_REX("🦖"),
    SAUROPOD("🦕"),
    OCTOPUS("🐙"),
    SQUID("🦑"),
    SHRIMP("🦐"),
    LOBSTER("🦞"),
    CRAB("🦀"),
    BLOWFISH("🐡"),
    TROPICAL_FISH("🐠"),
    FISH("🐟"),
    DOLPHIN("🐬"),
    SPOUTING_WHALE("🐳"),
    WHALE("🐋"),
    SHARK("🦈"),
    CROCODILE("🐊"),
    TIGER("🐅"),
    LEOPARD("🐆"),
    ZEBRA("🦓"),
    GORILLA("🦍"),
    CACTUS("🌵"),
    CHRISTMAS_TREE("🎄"),
    EVERGREEN_TREE("🌲"),
    DECIDUOUS_TREE("🌳"),
    PALM_TREE("🌴"),
    SEEDLING("🌱"),
    HERB("🌿"),
    SHAMROCK("☘️"),
    FOUR_LEAF_CLOVER("🍀"),
    PINE_DECORATION("🎍"),

    GREEN_APPLE("🍏"),
    RED_APPLE("🍎"),
    PEAR("🍐"),
    ORANGE("🍊"),
    LEMON("🍋"),
    BANANA("🍌"),
    WATERMELON("🍉"),
    GRAPES("🍇"),
    STRAWBERRY("🍓"),
    BLUEBERRIES("🫐"),
    MELON("🍈"),
    CHERRIES("🍒"),
    PEACH("🍑"),
    MANGO("🥭"),
    PINEAPPLE("🍍"),
    COCONUT("🥥"),
    KIWI("🥝"),
    TOMATO("🍅"),
    EGGPLANT("🍆"),
    AVOCADO("🥑"),
    BROCCOLI("🥦"),
    LEAFY_GREEN("🥬"),
    CUCUMBER("🥒"),
    HOT_PEPPER("🌶️"),
    BELL_PEPPER("🫑"),
    CORN("🌽"),
    CARROT("🥕"),
    OLIVE("🫒"),
    GARLIC("🧄"),
    ONION("🧅"),
    POTATO("🥔"),
    SWEET_POTATO("🍠"),
    CROISSANT("🥐"),
    BAGUETTE("🥖"),
    FLATBREAD("🫓"),
    PRETZEL("🥨"),
    BAGEL("🥯"),
    PANCAKES("🥞"),
    WAFFLE("🧇"),
    CHEESE_WEDGE("🧀"),
    MEAT_ON_BONE("🍖"),
    POULTRY_LEG("🍗"),
    CUT_OF_MEAT("🥩"),
    BACON("🥓"),
    HAMBURGER("🍔"),
    FRENCH_FRIES("🍟"),
    PIZZA("🍕"),
    HOT_DOG("🌭"),
    SANDWICH("🥪"),
    TACO("🌮"),

    SOCCER_BALL("⚽"),
    BASKETBALL("🏀"),
    AMERICAN_FOOTBALL("🏈"),
    BASEBALL("⚾"),
    SOFTBALL("🥎"),
    TENNIS("🎾"),
    VOLLEYBALL("🏐"),
    RUGBY_FOOTBALL("🏉"),
    FLYING_DISC("🥏"),
    BILLIARDS("🎱"),
    YO_YO("🪀"),
    PING_PONG("🏓"),
    BADMINTON("🏸"),
    ICE_HOCKEY("🏒"),
    FIELD_HOCKEY("🏑"),
    LACROSSE("🥍"),
    CRICKET_GAME("🏏"),
    BOOMERANG("🪃"),
    GOAL_NET("🥅"),
    FLAG_IN_HOLE("⛳"),
    KITE("🪁"),
    BOW_AND_ARROW("🏹"),
    FISHING_POLE("🎣"),
    DIVING_MASK("🤿"),
    BOXING_GLOVE("🥊"),
    MARTIAL_ARTS_UNIFORM("🥋"),
    RUNNING_SHIRT("🎽"),
    SKATEBOARD("🛹"),
    ROLLER_SKATE("🛼"),
    SLED("🛷"),
    ICE_SKATE("⛸️"),
    CURLING_STONE("🥌"),
    DIRECT_HIT("🎯"),
    YO_YO_ALT("🪀"),
    VIDEO_GAME("🎮"),
    GAME_DIE("🎲"),
    PUZZLE("🧩"),
    CHESS_PAWN("♟️"),
    PERFORMING_ARTS("🎭"),
    ARTIST_PALETTE("🎨"),

    CAR("🚗"),
    TAXI("🚕"),
    SUV("🚙"),
    BUS("🚌"),
    TROLLEYBUS("🚎"),
    RACING_CAR("🏎️"),
    POLICE_CAR("🚓"),
    AMBULANCE("🚑"),
    FIRE_ENGINE("🚒"),
    MINIVAN("🚐"),
    DELIVERY_TRUCK("🚚"),
    ARTICULATED_LORRY("🚛"),
    TRACTOR("🚜"),
    MOTOR_SCOOTER("🛵"),
    MOTORCYCLE("🏍️"),
    AUTO_RICKSHAW("🛺"),
    BICYCLE("🚲"),
    SCOOTER("🛴"),
    ONCOMING_POLICE_CAR("🚔"),
    ONCOMING_BUS("🚍"),
    AIRPLANE("✈️"),
    SMALL_AIRPLANE("🛩️"),
    ROCKET("🚀"),
    UFO("🛸"),
    HELICOPTER("🚁"),
    CANOE("🛶"),
    SAILBOAT("⛵"),
    SPEEDBOAT("🚤"),
    MOTOR_BOAT("🛥️"),
    PASSENGER_SHIP("🛳️"),
    HOUSE("🏠"),
    HOUSE_WITH_GARDEN("🏡"),
    OFFICE_BUILDING("🏢"),
    JAPANESE_POST_OFFICE("🏣"),
    HOSPITAL("🏥"),
    BANK("🏦"),
    HOTEL("🏨"),
    LOVE_HOTEL("🏩"),
    CONVENIENCE_STORE("🏪"),

    WATCH("⌚"),
    MOBILE_PHONE("📱"),
    LAPTOP("💻"),
    KEYBOARD("⌨️"),
    DESKTOP("🖥️"),
    PRINTER("🖨️"),
    MOUSE("🖱️"),
    FLOPPY_DISK("💾"),
    CD("💿"),
    DVD("📀"),
    CAMERA("📷"),
    VIDEO_CAMERA("🎥"),
    MAGNIFYING_GLASS_LEFT("🔍"),
    LIGHT_BULB("💡"),
    FLASHLIGHT("🔦"),
    BLUE_BOOK("📘"),
    BOOKS("📚"),
    MEMO("📝"),
    PENCIL("✏️"),
    FOUNTAIN_PEN("✒️"),
    PEN("🖊️"),
    PAINTBRUSH("🖌️"),
    CRAYON("🖍️"),
    PAPERCLIP("📎"),
    SCISSORS("✂️"),
    LOCK("🔒"),
    KEY("🔑"),
    HAMMER("🔨"),
    PICK("⛏️"),
    HAMMER_AND_PICK("⚒️"),
    TOOLS("🛠️"),
    WRENCH("🔧"),
    NUT_AND_BOLT("🔩"),
    GEAR("⚙️"),
    CLAMP("🗜️"),
    SATELLITE_ANTENNA("📡"),
    SYRINGE("💉"),
    PILL("💊"),
    DOOR("🚪"),
    BED("🛏️"),
    TOILET("🚽"),

    RED_HEART("❤️"),
    ORANGE_HEART("🧡"),
    YELLOW_HEART("💛"),
    GREEN_HEART("💚"),
    BLUE_HEART("💙"),
    PURPLE_HEART("💜"),
    BROWN_HEART("🤎"),
    BLACK_HEART("🖤"),
    WHITE_HEART("🤍"),
    BROKEN_HEART("💔"),
    HEART_EXCLAMATION("❣️"),
    TWO_HEARTS("💕"),
    REVOLVING_HEARTS("💞"),
    BEATING_HEART("💓"),
    GROWING_HEART("💗"),
    SPARKLING_HEART("💖"),
    HEART_WITH_ARROW("💘"),
    HEART_WITH_RIBBON("💝"),
    HEART_DECORATION("💟"),
    PEACE_SYMBOL("☮️"),
    LATIN_CROSS("✝️"),
    STAR_AND_CRESCENT("☪️"),
    OM_SYMBOL("🕉️"),
    WHEEL_OF_DHARMA("☸️"),
    STAR_OF_DAVID("✡️"),
    SIX_POINTED_STAR("🔯"),
    PLACE_OF_WORSHIP("🛐"),
    ATOM_SYMBOL("⚛️"),
    ARIES("♈"),
    TAURUS("♉"),
    GEMINI("♊"),
    CANCER("♋"),
    LEO("♌"),
    VIRGO("♍"),
    LIBRA("♎"),
    SCORPIO("♏"),
    SAGITTARIUS("♐"),
    CAPRICORN("♑"),
    AQUARIUS("♒"),
    PISCES("♓"),
    OPHIUCHUS("⛎"),

    RED_SQUARE("🟥"),
    BLUE_SQUARE("🟦"),
    GREEN_SQUARE("🟩"),
    ORANGE_SQUARE("🟧"),
    YELLOW_SQUARE("🟨"),
    PURPLE_SQUARE("🟪"),
    BROWN_SQUARE("🟫"),
    BLACK_SQUARE("⬛"),
    WHITE_SQUARE("⬜"),

    // دایره‌ها
    RED_CIRCLE("🔴"),
    BLUE_CIRCLE("🔵"),
    GREEN_CIRCLE("🟢"),
    ORANGE_CIRCLE("🟠"),
    YELLOW_CIRCLE("🟡"),
    PURPLE_CIRCLE("🟣"),
    BROWN_CIRCLE("🟤"),

    // دسته‌بندی جدید: نمادهای بازی (Game Symbols)
    BRICK("🧱"),
    GEM("💎"),
    CHEST("🎁"),
    ROCK("🪨"),
    LOCKED("🔒"),
    TREE("🌲"),
    WATER("🌊"),
    MOUNTAIN("⛰️"),
    GRASS("🌿"),

    WAVE("🌊"),
    DROPLET("💧"),
    WATER_WAVE("〰️"),
    WATERFALL("🌊"), // (جایگزین: برخی فونت‌ها از 🌊 برای آبشار استفاده می‌کنند)
    ICE("🧊"),
    SNOWFLAKE("❄️"),
    CLOUD_WITH_RAIN("🌧️"),
    HIGH_VOLTAGE("⚡"), // (برای رعد و برق روی آب)

    BEACH("🏖️"),
    ISLAND("🏝️"),
    DESERT_ISLAND("🏜️"),
    FOGGY("🌫️"), // (مه روی آب)


    //FISH("🐟"),
    //TROPICAL_FISH("🐠"),
//    BLOWFISH("🐡"),
//    SHARK("🦈"),
//    OCTOPUS("🐙"),
//    SQUID("🦑"),
//    SHRIMP("🦐"),
//    CRAB("🦀"),
//    LOBSTER("🦞"),
//    DOLPHIN("🐬"),
//    WHALE("🐋"),
    //SPOUTING_WHALE("🐳"),
    SEAL("🦭"),
    //TURTLE("🐢"),
    SEAHORSE("🪼"),
    STARFISH("🌟"),
    CORAL("🪸"),
    SHELL("🐚"),

    // فعالیت‌های آبی
//    SAILBOAT("⛵"),
//    SPEEDBOAT("🚤"),
    FERRY("⛴️"),
    SHIP("🚢"),
    ANCHOR("⚓"),
    SCUBA_MASK("🤿"),
    LIFE_JACKET("🦺"),
    //FISHING_POLE("🎣"),

//    GRAPES("🍇"),
//    MELON("🍈"),
//    WATERMELON("🍉"),
    TANGERINE("🍊"),
//    LEMON("🍋"),
//    BANANA("🍌"),
//    PINEAPPLE("🍍"),
//    MANGO("🥭"),
//    RED_APPLE("🍎"),
//    GREEN_APPLE("🍏"),
//    PEAR("🍐"),
//    PEACH("🍑"),
//    CHERRIES("🍒"),
//    STRAWBERRY("🍓"),
//    BLUEBERRIES("🫐"),
//    KIWI("🥝"),
//    TOMATO("🍅"),

//    // سبزیجات
//    EGGPLANT("🍆"),
//    AVOCADO("🥑"),
//    BROCCOLI("🥦"),
//    LEAFY_GREEN("🥬"),
//    CUCUMBER("🥒"),
//    HOT_PEPPER("🌶️"),
//    BELL_PEPPER("🫑"),
//    CORN("🌽"),
//    CARROT("🥕"),
//    OLIVE("🫒"),
//    GARLIC("🧄"),
//    ONION("🧅"),
//    POTATO("🥔"),
//    SWEET_POTATO("🍠"),

    // غذاهای آماده
//    CROISSANT("🥐"),
//    BAGUETTE("🥖"),
//    FLATBREAD("🫓"),
//    PRETZEL("🥨"),
//    BAGEL("🥯"),
//    PANCAKES("🥞"),
//    WAFFLE("🧇"),
    CHEESE("🧀"),
//    MEAT_ON_BONE("🍖"),
//    POULTRY_LEG("🍗"),
//    CUT_OF_MEAT("🥩"),
//    BACON("🥓"),
//    HAMBURGER("🍔"),
//    FRENCH_FRIES("🍟"),
//    PIZZA("🍕"),
//    HOT_DOG("🌭"),
//    SANDWICH("🥪"),
//    TACO("🌮"),
    BURRITO("🌯"),
    TAMALE("🫔"),
    //FALAFEL("🧆"),
    EGG("🥚"),
    COOKING("🍳"),
    SHALLOW_PAN("🥘"),
    POT_OF_FOOD("🍲"),
    FONDUE("🫕"),
    BOWL_WITH_SPOON("🥣"),
    GREEN_SALAD("🥗"),
    POPCORN("🍿"),
    BUTTER("🧈"),
    SALT("🧂"),
    CANNED_FOOD("🥫"),

    // نوشیدنی‌ها
    BABY_BOTTLE("🍼"),
    GLASS_OF_MILK("🥛"),
    HOT_BEVERAGE("☕"),
    TEAPOT("🫖"),
    TEACUP("🍵"),
    SAKE("🍶"),
    BOTTLE_POPPING("🍾"),
    WINE_GLASS("🍷"),
    COCKTAIL("🍸"),
    TROPICAL_DRINK("🍹"),
    BEER_MUG("🍺"),
    CLINKING_BEERS("🍻"),
    CLINKING_GLASSES("🥂"),
    TUMBLER_GLASS("🥃"),
    POURING_LIQUID("🫗"),
    CUP_WITH_STRAW("🥤"),
    BUBBLE_TEA("🧋"),
    BEVERAGE_BOX("🧃"),
    MATE("🧉"),
    //ICE("🧊"),

    // دسرها
    SOFT_ICE_CREAM("🍦"),
    SHAVED_ICE("🍧"),
    ICE_CREAM("🍨"),
    DOUGHNUT("🍩"),
    COOKIE("🍪"),
    BIRTHDAY_CAKE("🎂"),
    SHORTCAKE("🍰"),
    CUPCAKE("🧁"),
    PIE("🥧"),
    CHOCOLATE("🍫"),
    CANDY("🍬"),
    LOLLIPOP("🍭"),
    CUSTARD("🍮"),
    HONEY_POT("🍯"),

    // ظروف و ابزار
    FORK_KNIFE("🍴"),
    FORK_KNIFE_PLATE("🍽️"),
    SPOON("🥄"),
    KITCHEN_KNIFE("🔪"),
    JAR("🫙"),
    TRUE("✅"),
    FALSE("❌"),

    // دسته‌بندی: سنگ‌ها و مواد معدنی (Stones & Minerals)
//    ROCK("🪨"),
//    BRICK("🧱"),
    GEM_STONE("💎"),
//    PICK("⛏️"),
//    MOUNTAIN("⛰️"),
    VOLCANO("🌋"),
    MOAI("🗿");

    private final String symbol;

    Emoji(String symbol) {
        this.symbol = symbol;
    }

    public String getSymbol() {
        return symbol;
    }

    public static String getFormattedGuidance() {
        TileType[] values = TileType.values();
        StringBuilder output = new StringBuilder();
        for (TileType value : values) {
            String formattedLine = String.format("%-" + 15 + "s", value.name());
            output.append(formattedLine).append(" : ").append(value.getSymbol()).append("\n");
        }
        return output.toString();
    }


}